Exercise 7
===
Create a RNN that can learn a Reber grammer (http://www.willamette.edu/~gorr/classes/cs449/reber.html)

In [3]:
import random

seed = 42
random.seed(seed)

start_symbol = "b"
end_symbol = "e"

symbols = [start_symbol, "t", "p", "s", "x", "v", end_symbol]

def get_next_symbols(previous_symbol, current_symbol):
    if current_symbol == None and previous_symbol == None:
        return [start_symbol]
    elif current_symbol == start_symbol:
        return ["t", "p"]
    elif current_symbol == "t":
        if previous_symbol == start_symbol:
            return ["s", "x"]
        elif previous_symbol in ["p", "x", "t"]:
            return ["t", "v"]
        else:
            raise Exception("Invalid grammar.")
    elif current_symbol == "p":
        if previous_symbol == start_symbol:
            return ["t", "v"]
        elif previous_symbol == "v":
            return ["x", "s"]
        else:
            raise Exception("Invalid grammar.")
    elif current_symbol == "s":
        if previous_symbol in ["t", "s"]:
            return ["x", "s"]
        elif previous_symbol in ["x", "p"]:
            return [end_symbol]
        else:
            raise Exception("Invalid grammar.")
    elif current_symbol == "x":
        if previous_symbol in ["t", "s"]:
            return ["x", "s"]
        elif previous_symbol in ["x", "p"]:
            return ["t", "v"]
        else:
            raise Exception("Invalid grammar.")
    elif current_symbol == "v":
        if previous_symbol in ["t", "x", "p"]:
            return ["p", "v"]
        elif previous_symbol == "v":
            return [ end_symbol ]
        else:
            raise Exception("Invalid grammar.")
    elif current_symbol == end_symbol:
        return []
    else:
        raise Exception("Invalid symbols: %s and %s." % (previous_symbol, current_symbol))

def get_next_symbols_for_string(reber_str):
    previous_symbol = reber_str[-2] if len(reber_str) >= 2 else None
    current_symbol = reber_str[-1] if len(reber_str) >= 1 else None
    return get_next_symbols(previous_symbol, current_symbol)

def create_reber_string():
    reber_str = ""
    while not reber_str.endswith(end_symbol):
        reber_str += random.choice(get_next_symbols_for_string(reber_str))
    return reber_str

def is_valid_reber_string(value):
    index = 0
    while index < len(value):
        current = value[index]
        next_symbols = get_next_symbols_for_string(value[:index] if index != 0 else "")
        if current not in next_symbols:
            return False
        index += 1
    return True

In [163]:
import numpy as np
import tensorflow as tf

np.random.seed(seed)
tf.set_random_seed(seed)

def create_reber_strings(size):
    strings = []
    while len(strings) < size:
        new_string = create_reber_string()
        if new_string not in strings:
            strings.append(new_string)
    return strings

def invalidate_reber_string(value):
    while is_valid_reber_string(value):
        char_list = list(value)
        char_list[random.randint(0, len(value) - 1)] = random.choice(symbols)
        value = "".join(char_list)
    return value

def invalidate_reber_strings(strings):
    return [invalidate_reber_string(x) for x in strings]

def symbol_to_one_hot_encoding(symbol):
    one_hot_encoding = np.zeros((len(symbols)), dtype=np.int8)
    if symbol != '':
        one_hot_encoding[symbols.index(symbol)] = 1
    return one_hot_encoding

def prep_strings_for_model(strings, sequence_length):
    padded_strings = np.array([np.pad(list(x), (0, (sequence_length - len(x)) % sequence_length), 'constant') for x in strings])
    sequences = np.array([np.array(list(map(symbol_to_one_hot_encoding, x))) for x in padded_strings])
    return sequences

def generate_dataset(size, error_ratio = 0.5):
    if size % 2 != 0:
        raise Exception("size must be a multiple of 2.")
    correct_strings = create_reber_strings(int(size * error_ratio))
    incorrect_strings = invalidate_reber_strings(correct_strings)
    correct_val = True
    incorrect_val = False
    targets = np.array(([ correct_val ] * len(correct_strings)) + ([ incorrect_val ] * len(incorrect_strings)))
    indices = np.random.permutation(size)
    strings = correct_strings + incorrect_strings
    sequence_lengths = np.array([len(x) for x in strings])
    max_sequence_length = max(sequence_lengths)
    strings = prep_strings_for_model(strings, max_sequence_length)
    #print(strings[0])
    return strings[indices], sequence_lengths, targets[indices]

train_size = 1200
validation_size = int(train_size * 0.2)
test_size = int(train_size * 0.2)

all_strings, sequence_lengths, all_targets = generate_dataset(train_size + validation_size + test_size)
train_X = all_strings[:train_size]
train_seq_lengths = sequence_lengths[:train_size]
train_y = all_targets[:train_size]
validation_X = all_strings[train_size:train_size+validation_size]
validation_seq_lengths = sequence_lengths[train_size:train_size+validation_size]
validation_y = all_targets[train_size:train_size+validation_size]
test_X = all_strings[train_size+validation_size:train_size+validation_size+test_size]
test_seq_lengths = sequence_lengths[train_size+validation_size:train_size+validation_size+test_size]
test_y = all_targets[train_size+validation_size:train_size+validation_size+test_size]

#print(list(map(symbol_to_one_hot_encoding, create_reber_string())))
print("train size", len(train_X), "validation size", len(validation_X), "test size", len(test_X))
print("all_strings.shape", all_strings.shape)
#print("string shapes", list(map(lambda a: a.shape, all_strings)))
print("Example sequence:", all_strings[1], all_targets[1])
#print("sequence_lengths", sequence_lengths)

max_sequence_length = train_X[0].shape[0]
print("The max sequence length is", max_sequence_length)

train size 1200 validation size 240 test size 240
all_strings.shape (1680, 38, 7)
Example sequence: [[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] True
The max sequence length is 38


In [201]:
import math
from sklearn.base import BaseEstimator, ClassifierMixin

def he_normal_initialisation(n_inputs, n_outputs):
    stddev = np.power(2 / (n_inputs + n_outputs), 1 / np.sqrt(2))
    # truncated normal distributions limit the size of the weights, speeding up the training time.
    return tf.truncated_normal((n_inputs, n_outputs), stddev=stddev)

def he_uniform_initialisation(n_inputs, n_outputs):
    r = np.power(6 / (n_inputs + n_outputs), 1 / np.sqrt(2))
    # truncated normal distributions limit the size of the weights, speeding up the training time.
    return tf.random_uniform((n_inputs, n_outputs), -r, r)

def create_next_batch_fn(data, sequence_lengths, targets, batch_size):
    assert len(data) == len(sequence_lengths) and len(data) == len(targets)
    current_batch = 0
    def next_batch():
        nonlocal current_batch
        i = current_batch
        #print(current_batch)
        current_batch = (current_batch + batch_size) % len(data)
        return data[i:i+batch_size], sequence_lengths[i:i+batch_size], targets[i:i+batch_size]
    return next_batch

class RnnClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, n_steps, learning_rate=0.001, n_neurons=2):
        self.n_steps = n_steps
        self.learning_rate = learning_rate
        self.n_neurons = n_neurons
        self._build_graph()

    def _build_graph(self):
        n_inputs = 1
        self.n_output = 1
        self.batch_size = 50
        
        self.x = tf.placeholder(tf.float32, shape=(None, self.n_steps, len(symbols)), name="input")
        self.sequence_length = tf.placeholder(tf.int32, shape=(None), name="sequence_length")
        self.y = tf.placeholder(tf.bool, shape=(None), name="y")

        with tf.name_scope("rnn"):
            cell = tf.contrib.rnn.OutputProjectionWrapper(
                tf.contrib.rnn.GRUCell(num_units=self.n_neurons, activation=tf.nn.relu),
                output_size=self.n_output)
            outputs, last_outputs = tf.nn.dynamic_rnn(cell, self.x, dtype=tf.float32, sequence_length=self.sequence_length)
            #print("last_outputs.shape", last_outputs.shape)
            W = tf.Variable(tf.truncated_normal((self.n_neurons, self.n_output), stddev=10.1), name="weights")
            b = tf.Variable(tf.zeros([self.n_output]), name="biases")
            self.is_reber_string = tf.nn.sigmoid(tf.matmul(last_outputs, W) + b)
            self.evaluation = self.is_reber_string

        with tf.name_scope("loss"):
            target = tf.cast(self.y, tf.float32)
            self.loss = tf.reduce_mean(tf.square(self.is_reber_string - target))

        with tf.name_scope("training"):
            optimizer = tf.train.AdamOptimizer(learning_rate=self.learning_rate)
            self.training_op = optimizer.minimize(self.loss)

        with tf.name_scope("eval"):
            midpoint = 0.5
            correctness = tf.equal((self.is_reber_string >= midpoint), self.y)
            self.accuracy = tf.reduce_mean(tf.cast(correctness, tf.float32)) * 100
            
        self.init = tf.global_variables_initializer()

    def fit(self, X, sequence_lengths, y, valid_X, valid_sequence_length, valid_y, epochs = 20):
        saver = tf.train.Saver()

        interim_checkpoint_path = "./checkpoints/reber_rnn_model.ckpt"
        early_stopping_checkpoint_path = "./checkpoints/reber_rnn_model_early_stopping.ckpt"

        from datetime import datetime

        now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
        root_logdir = "tf_logs"
        log_dir = "{}/run-{}/".format(root_logdir, now)

        loss_summary = tf.summary.scalar('loss', self.loss)
        accuracy_summary = tf.summary.scalar("accuracy", self.accuracy)
        summary_op = tf.summary.merge([loss_summary, accuracy_summary])
        file_writer = tf.summary.FileWriter(log_dir, tf.get_default_graph())
        
        n_batches = int(np.ceil(len(X) // self.batch_size))
        next_batch = create_next_batch_fn(X, sequence_lengths, y, self.batch_size)
            
        early_stopping_check_frequency = self.batch_size // 4
        early_stopping_check_limit = self.batch_size * 4

        sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
        self.session = sess
        sess.run(self.init)
        #saver.restore(sess, interim_checkpoint_path)

        best_validation_acc = 0.0
        best_validation_step = 0
        for epoch in range(epochs):
            print("epoch", epoch)
            for batch_index in range(n_batches):
                step = epoch * n_batches + batch_index
                X_batch, seq_length_batch, y_batch = next_batch()
                #print("training batch", X_batch.shape, seq_length_batch.shape, y_batch.shape)
                #print(seq_length_batch)
                if batch_index % 10 == 0:
                    summary_str = summary_op.eval(session=sess, feed_dict={self.x: X_batch, self.sequence_length: seq_length_batch, self.y: y_batch})
                    file_writer.add_summary(summary_str, step)
                t, l, a, irs = sess.run([self.training_op, self.loss, self.accuracy, self.is_reber_string], feed_dict={self.x: X_batch, self.sequence_length: seq_length_batch, self.y: y_batch})
                print("is_reber_string", irs)
                if batch_index % 10 == 0: print("loss:", l, "train accuracy:", a)
                # Early stopping check
                if batch_index % early_stopping_check_frequency == 0:
                    validation_acc = self.prediction_accuracy(valid_X, valid_sequence_length, valid_y)
                    print("validation accuracy", validation_acc)
                    if validation_acc > best_validation_acc:
                        saver.save(sess, early_stopping_checkpoint_path)
                        best_validation_acc = validation_acc
                        best_validation_step = step
                    elif step >= (best_validation_step + early_stopping_check_limit):
                        print("Stopping early during epoch", epoch)
                        break
            else:
                continue
            break
            save_path = saver.save(sess, interim_checkpoint_path)
        saver.restore(sess, early_stopping_checkpoint_path)
        save_path = saver.save(sess, "./checkpoints/reber_rnn_model_final.ckpt")
            
    def predict_proba(self, X, sequence_lengths):
        dataset_size = X.shape[0]
        #print "dataset_size: ", dataset_size, " batch_size: ", batch_size
        predictions = np.ndarray(shape=(dataset_size, self.n_output), dtype=np.float32)
        steps = int(math.ceil(dataset_size / self.batch_size))
        #print "steps: ", steps
        for step in range(steps):
            offset = (step * self.batch_size)
            #print "offset ", offset
            data_end_index = min(offset + self.batch_size, dataset_size)
            batch_data = X[offset:data_end_index, :]
            feed_dict = {
                self.x: batch_data,
                self.sequence_length: sequence_lengths[offset:data_end_index]
            }
            predictions[offset:data_end_index, :] = self.evaluation.eval(session=self.session, feed_dict=feed_dict)
        #print("predict_proba", predictions)
        return predictions

    def predict(self, X, sequence_lengths):
        return np.argmax(self.predict_proba(X, sequence_lengths), axis=1)
    
    def _prediction_accuracy(self, predictions, y):
        midpoint = 0.5
        return (np.sum(((predictions.reshape((-1)) >= midpoint) == y).astype(float))
              / predictions.shape[0]) * 100
    
    def prediction_accuracy(self, X, sequence_lengths, y):
        predictions = self.predict_proba(X, sequence_lengths)
        return self._prediction_accuracy(predictions, y)

In [203]:
tf.reset_default_graph()
rnn_classifier = RnnClassifier(max_sequence_length, learning_rate=0.1, n_neurons=1)

rnn_classifier.fit(train_X, train_seq_lengths, train_y, validation_X, validation_seq_lengths, validation_y)

epoch 0
is_reber_string [[ 0.27171969]
 [ 0.26977468]
 [ 0.40552872]
 [ 0.39243746]
 [ 0.40216869]
 [ 0.22505791]
 [ 0.32569757]
 [ 0.41433591]
 [ 0.41990414]
 [ 0.26267216]
 [ 0.38746017]
 [ 0.3275843 ]
 [ 0.33532089]
 [ 0.26526666]
 [ 0.42240983]
 [ 0.32142648]
 [ 0.40223342]
 [ 0.46738103]
 [ 0.4171024 ]
 [ 0.40818316]
 [ 0.27149683]
 [ 0.19902571]
 [ 0.4202264 ]
 [ 0.32638866]
 [ 0.30581349]
 [ 0.20250274]
 [ 0.3679662 ]
 [ 0.39265436]
 [ 0.3727057 ]
 [ 0.44178474]
 [ 0.31588826]
 [ 0.32954279]
 [ 0.38585621]
 [ 0.37711731]
 [ 0.27266547]
 [ 0.4517948 ]
 [ 0.38042128]
 [ 0.21507174]
 [ 0.31516486]
 [ 0.37223366]
 [ 0.31278583]
 [ 0.36081716]
 [ 0.32954279]
 [ 0.28156087]
 [ 0.4202264 ]
 [ 0.44489664]
 [ 0.39017123]
 [ 0.26557776]
 [ 0.3385376 ]
 [ 0.45439017]]
loss: 0.301744 train accuracy: 42.0
validation accuracy 52.9166666667
is_reber_string [[ 0.43639857]
 [ 0.40070537]
 [ 0.50283462]
 [ 0.49279541]
 [ 0.48303178]
 [ 0.46508244]
 [ 0.384296  ]
 [ 0.50981063]
 [ 0.3390466 ]
 [ 0

is_reber_string [[ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]
 [ 0.52389455]]
is_reber_string [[ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51617992]
 [ 0.51

validation accuracy 52.5
is_reber_string [[ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]
 [ 0.49528679]]
is_reber_string [[ 0.49698919]
 [ 0.49698919]
 [ 0.49698919]
 [ 0.49698919]
 [ 0.49698919]
 [ 0.49698919]
 [ 0.49698919]
 [ 0.49698919]
 [ 0.49698919]
 [ 0.49698919]
 [ 0.49698919]
 [ 0.49698919]
 [ 0.4969891

is_reber_string [[ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]
 [ 0.52035671]]
loss: 0.251229 train accuracy: 48.0
is_reber_string [[ 0.52284151]
 [ 0.52284151]
 [ 0.52284151]
 [ 0.52284151]
 [ 0.52284151]
 [ 0.52284151]
 [ 0.52284151]
 [ 0.52284151]
 [ 0.52284151]
 [ 0.52284151]
 [ 0.52284151]
 [ 0.52284151]
 

is_reber_string [[ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]
 [ 0.49268577]]
is_reber_string [[ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49416238]
 [ 0.49

is_reber_string [[ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]
 [ 0.51050675]]
loss: 0.25011 train accuracy: 50.0
is_reber_string [[ 0.50270146]
 [ 0.50270146]
 [ 0.50270146]
 [ 0.50270146]
 [ 0.50270146]
 [ 0.50270146]
 [ 0.50270146]
 [ 0.50270146]
 [ 0.50270146]
 [ 0.50270146]
 [ 0.50270146]
 [ 0.50270146]
 [

is_reber_string [[ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]
 [ 0.52430874]]
is_reber_string [[ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52495629]
 [ 0.52

validation accuracy 47.5
is_reber_string [[ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]
 [ 0.51668167]]
is_reber_string [[ 0.51849276]
 [ 0.51849276]
 [ 0.51849276]
 [ 0.51849276]
 [ 0.51849276]
 [ 0.51849276]
 [ 0.51849276]
 [ 0.51849276]
 [ 0.51849276]
 [ 0.51849276]
 [ 0.51849276]
 [ 0.51849276]
 [ 0.5184927

is_reber_string [[ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]
 [ 0.49624014]]
validation accuracy 52.5
is_reber_string [[ 0.49457666]
 [ 0.49457666]
 [ 0.49457666]
 [ 0.49457666]
 [ 0.49457666]
 [ 0.49457666]
 [ 0.49457666]
 [ 0.49457666]
 [ 0.49457666]
 [ 0.49457666]
 [ 0.49457666]
 [ 0.49457666]
 [ 0.4945766

is_reber_string [[ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]
 [ 0.51470047]]
epoch 6
is_reber_string [[ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]
 [ 0.51473671]

is_reber_string [[ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]
 [ 0.5002802]]
is_reber_string [[ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.50454205]
 [ 0.5045420

is_reber_string [[ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]
 [ 0.49417776]]
is_reber_string [[ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49283212]
 [ 0.49

is_reber_string [[ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]
 [ 0.52795988]]
is_reber_string [[ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52503449]
 [ 0.52

In [ ]:
rnn_classifier.predict_proba(train_X[:20], train_seq_lengths[:20])